### PR TITLE
Review and changes of basemodui and gameui

### PR DESCRIPTION
**Pull request by DucDuyGaming**
I might miss some part or also make mistake on some part here that I did not see, but I try as best as I can to be aware of those. I'll continue tomorrow, just merge this PR if you want

### CODE REVIEW

**Comment by DucDuyGaming** [comment]
In latter PR (if this PR is merged without further additional commits), I will try to make as little pull request as possible. I'm the guy who typically hoard up translations until it is time

**Comment by Blueberryy** [comment]
oh i just noticed this PR lol

**Comment by Blueberryy** [comment]
yeah i will be waiting for your new commits until you polish everything

**Comment by DucDuyGaming** [comment]
will send a message here when i finish with basemodui (around half way there but it feel like forever), and will ping you after gameui. while ill try my best to check for every things, there is no guarantee that it will be free of errors or nonsense wording. after you merge, i may perform one last very quick check on both file before i give out a ready sign in the main PR

**Comment by DucDuyGaming** [comment]
and i notice i just keep saying "PL" and not "PR"

**Comment by DucDuyGaming** [comment]
basemodui is done, time for gameui

also, [a commit](https://github.com/ReactiveDrop/reactivedrop_translations/commit/f55771c6176c757cd6732ed64d0dfe3a83795a67) 5 days ago introduce in 2 new strings in the middle of basemodui, which cause a confliction. i tried to solve it by myself by adding in those strings in the exact same line number and translated it but GitHub say no
image

**Comment by Blueberryy** [comment]
> basemodui is done, time for gameui
> 
> also, [a commit](https://github.com/ReactiveDrop/reactivedrop_translations/commit/f55771c6176c757cd6732ed64d0dfe3a83795a67) 5 days ago introduce in 2 new strings in the middle of basemodui, which cause a confliction. i tried to solve it by myself by adding in those strings in the exact same line number and translated it but GitHub say no image

Don't worry,  i think we will fix this after i merge your gameui check commits.

**Comment by DucDuyGaming** [comment]
gameui is done 
image
dont take the picture seriously

**Comment by Blueberryy** [comment]
> gameui is done 
> image
> dont take the picture seriously

Congratulations! I will merge that in my main PR and change PR to normal one so it can be merged. Thank you for checking all this ton of text

**Pull request merged**
